<a href="https://colab.research.google.com/github/Abitha09062002/Seizure_Detection_Hyperparameter/blob/main/Project/PG_ML_Random_Sens%2C_Spec%2C_F1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
d1=pd.read_csv('/content/drive/MyDrive/dataset-org.csv',header=None)
print(d1)

       0    1    2    3    4    5    6    7    8    9    ...  169  170  171  \
0      135  190  229  223  192  125   55   -9  -33  -38  ...  -17  -15  -31   
1      386  382  356  331  320  315  307  272  244  232  ...  164  150  146   
2      -32  -39  -47  -37  -32  -36  -57  -73  -85  -94  ...   57   64   48   
3     -105 -101  -96  -92  -89  -95 -102 -100  -87  -79  ...  -82  -81  -80   
4       -9  -65  -98 -102  -78  -48  -16    0  -21  -59  ...    4    2  -12   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
11495  -22  -22  -23  -26  -36  -42  -45  -42  -45  -49  ...   15   16   12   
11496  -47  -11   28   77  141  211  246  240  193  136  ...  -65  -33   -7   
11497   14    6  -13  -16   10   26   27   -9    4   14  ...  -65  -48  -61   
11498  -40  -25   -9  -12   -2   12    7   19   22   29  ...  121  135  148   
11499   29   41   57   72   74   62   54   43   31   23  ...  -59  -25   -4   

       172  173  174  175  176  177  178  
0      -

In [ ]:
X=pd.DataFrame(d1.iloc[:,:-1].values)
Y=d1.iloc[:,-1].values

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state = 0 )

In [ ]:
print(X_train)

       0    1    2    3    4    5    6    7    8    9    ...  168  169  170  \
5979    10   18   37   32   28   28   43   56   64   53  ...   72   57   31   
4731    22   23   16    8   -5  -11  -10    5   16   25  ...  -42   -8   40   
6406   -18  -12   -8   -7   -2    4    9   21   31   37  ...   11    1  -15   
8207   180  211  260  390  518  616  588  443  273  117  ...  -62  -67  -75   
1592    16  -13  -25  -14   11   34   51   34    2  -28  ...   11  -15  -21   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
4859   -33  -33  -38  -40  -38  -30  -38  -36  -37  -40  ...  -22  -24  -29   
3264   -13  -10  -15  -19  -26  -24  -35  -39  -42  -54  ...  -37  -52  -65   
9845    18   20   26   28   31   29   28   19   13    0  ...  -39  -35  -37   
10799  285  282  311  361  427  478  577  634  448    6  ...  274  249  249   
2732  -118   55  272  439  475  404  266  146   45  -29  ...  -79  -93 -134   

       171  172  173  174  175  176  177  
5979    

In [ ]:
print(X_test)

       0    1    2    3    4    5    6    7    8    9    ...  168  169  170  \
4313   -16   -3  -16  -13  -11   -6   23   38   46   53  ...  102  100   92   
4340   154  144  132  115   98   79   60   43   22    2  ... -230  -38  139   
10982    3    1    3   -3   -5   -7   -8   -4  -10   -9  ...    0   -2    5   
7986   -32  -30  -33  -28  -33  -32  -35  -40  -41  -44  ...  -18  -10  -11   
6263  -124 -123 -103 -102 -108  -74   -4   32   69   86  ...  -28  -15  -22   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
11070  -16   10   29   23    0  -18  -48  -50  -61  -71  ...   30    4   13   
7920   -36  -30  -21  -16  -16  -23  -23  -31  -40  -52  ...  -47  -51  -60   
2081   -29  -46  -48  -43  -33  -22  -25  -22  -33  -33  ...  -81  -80  -69   
5257   -40  -69  -84  -80  -64  -38  -21   13   47   74  ...   64   59   50   
3750  -394 -520 -592 -589 -530 -445 -366 -260 -123    5  ...  280  270  232   

       171  172  173  174  175  176  177  
4313    

In [ ]:
print(Y_train)

[0 0 0 ... 0 1 1]


In [ ]:
print(Y_test)

[0 1 0 ... 0 0 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
import tensorflow as tf

In [ ]:
import keras  as ke

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
classifier = Sequential()

In [ ]:
classifier.add(Dense(units= 100, kernel_initializer = 'uniform', activation = 'relu', input_dim = 178))

In [ ]:
classifier.add(Dense(units = 100,kernel_initializer = 'uniform', activation = 'relu'))

In [ ]:
classifier.add(Dense(units = 1,kernel_initializer   = 'uniform', activation = 'sigmoid'))

In [ ]:
classifier.compile(optimizer = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
classifier.fit(X_train, Y_train, batch_size = 10, epochs = 30)

Epoch 1/30
920/920 [==============================] - 2s 2ms/step - loss: 0.4919 - accuracy: 0.8280
Epoch 2/30
920/920 [==============================] - 2s 2ms/step - loss: 0.2393 - accuracy: 0.9382
Epoch 3/30
920/920 [==============================] - 2s 2ms/step - loss: 0.1545 - accuracy: 0.9564
Epoch 4/30
920/920 [==============================] - 1s 2ms/step - loss: 0.1207 - accuracy: 0.9649
Epoch 5/30
920/920 [==============================] - 1s 2ms/step - loss: 0.1024 - accuracy: 0.9674
Epoch 6/30
920/920 [==============================] - 1s 2ms/step - loss: 0.0912 - accuracy: 0.9705
Epoch 7/30
920/920 [==============================] - 1s 2ms/step - loss: 0.0836 - accuracy: 0.9726
Epoch 8/30
920/920 [==============================] - 1s 2ms/step - loss: 0.0795 - accuracy: 0.9752
Epoch 9/30
920/920 [==============================] - 2s 2ms/step - loss: 0.0734 - accuracy: 0.9763
Epoch 10/30
920/920 [==============================] - 2s 2ms/step - loss: 0.0710 - accuracy: 0.9777

In [ ]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [ ]:
y_pred

array([[False],
       [ True],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test,y_pred)

[[1838   16]
 [  31  415]]


0.9795652173913043

In [ ]:
sensitivity1=(1836/(1836+18))
print(sensitivity1)

0.9902912621359223


In [ ]:
specificity1=(411/(411+35))
print(specificity1)

0.92152466367713


In [ ]:
#precision=(TP/(TP+FP))
precision1=(1836/(1836+18))
print(precision1)

0.9902912621359223


In [ ]:
#recall=(TP/(TP+FN))
recall1=(1836/(1836+35))
print(recall1)

0.9812934259754142


In [ ]:
F1Score=2*(precision1*recall1/(precision1+recall1))
print(F1Score)

0.985771812080537
